### ISSUE TITLE
`set_xcconfig_value` will only update not set a value

### ISSUE THREAD

**Issue by steprescott** [sovcharenko/fastlane-plugin-xcconfig#1]
When using `set_xcconfig_value` with a `.xcconfig` file that doesn't already contain an entry for the given `name` it will fail.

`app.xcconfig` at this moment is empty.

#### Command
```ruby
set_xcconfig_value(
  path: "app.xcconfig", 
  name: 'PRODUCT_BUNDLE_IDENTIFIER', 
  value: 'com.some.app'
)
```
#### Result
```
Couldn't find 'PRODUCT_BUNDLE_IDENTIFIER' in app.xcconfig
```
#### Expected result
As the function name is `set_xcconfig_value` not `update_xcconfig_value` I would expect for the name & value to be written regardless if it currently exists in the given `.xcconfig` file.

**Comment by freemansion** [comment]
Having the same issue.
@sovcharenko are you planning to merge  #2 in the nearest time?

**Comment by sovcharenko** [comment]
Apologies for the delay - I'll review this later this week.
