### ISSUE TITLE
Specify xcconfig path issue

### ISSUE THREAD

**Issue by romanbaitaliuk** [sovcharenko/fastlane-plugin-xcconfig#3]
Hi Sergii,

I having issue running fastlane:

`Couldn't find xcconfig file at path '../../Configs/Base.xcconfig'`

Is it possible to specify path like this? My "Configs" folder is outside of fastlane directory.

This is my source code:
```
private_lane :update_app_group_identifier do
    update_xcconfig_value(
      path: '../../Configs/Base.xcconfig',
      name: 'APP_GROUP_ID',
      value: ENV['APP_GROUP_ID']
    )
  end
```

Thanks,
Roman

**Comment by logalize** [comment]
+1
path: '../MY_PROJECT_NAME/Supporting\ Files/Config/Config.xcconfig'
it doesn't work for me either

**Comment by sovcharenko** [comment]
Fastfile is plain ruby script and you're free to use ruby utils there. Try

"#{__DIR__}/../MY_PROJECT_NAME/Supporting Files/Config/Config.xcconfig"

If you're trying to resolve path relative to the current file's path.
